### ISSUE TITLE
Dont work with this module

### ISSUE THREAD

**Issue by mageuser** [staempfli/magento2-module-gdpr#1]
Hello, im using Magento 2.2.3

Since i'm showing out of stock products i need move their to the end, so im using this module:
https://github.com/bengower/OosBottom
If i install your module stop work, can you help? 

Thanks.

**Comment by mhauri** [comment]
Hello @kauansoft thank you for your feedback, as you may noticed, this module is still work in progress. So far I can't see why this module should interference with the one from bengower.

I close the issue for now. If you have further issues please use the issue template and add more details like a detailed error report or something similar.

Thanks
